#!/usr/bin/env bash
# Shared virtual-display helpers for RenForge cloud/CI scripts.
# Source this file; do not execute it.
#
# DISPLAY set by `bash scripts/setup_cloud_env.sh` dies with that process.
# These helpers persist the chosen display under ~/.cache/renforge/cloud.env
# and rediscover a running Xvfb so later shells (smoke test, Cursor start)
# do not depend on a leftover export.

RENFORGE_CLOUD_ENV_FILE="${RENFORGE_CLOUD_ENV_FILE:-${HOME}/.cache/renforge/cloud.env}"
RENFORGE_DEFAULT_DISPLAY="${RENFORGE_DEFAULT_DISPLAY:-:99}"
RENFORGE_XVFB_SCREEN="${RENFORGE_XVFB_SCREEN:-1920x1080x24}"

_display_accessible() {
    local display="$1"
    command -v xdpyinfo >/dev/null 2>&1 || return 1
    xdpyinfo -display "$display" >/dev/null 2>&1
}

load_renforge_cloud_env() {
    if [ -f "$RENFORGE_CLOUD_ENV_FILE" ]; then
        # shellcheck disable=SC1090
        . "$RENFORGE_CLOUD_ENV_FILE"
    fi
}

persist_renforge_cloud_env() {
    mkdir -p "$(dirname "$RENFORGE_CLOUD_ENV_FILE")"
    umask 077
    cat > "$RENFORGE_CLOUD_ENV_FILE" <<EOF
# Generated by RenForge cloud setup. Safe to source from later shells.
export DISPLAY=${DISPLAY:-$RENFORGE_DEFAULT_DISPLAY}
EOF
}

_start_xvfb() {
    local display="$1"
    if ! command -v Xvfb >/dev/null 2>&1; then
        log_error "Xvfb not found. Install xvfb (Debian/Ubuntu) or xorg-x11-server-Xvfb (RHEL)."
        return 1
    fi
    log_info "Starting Xvfb on display ${display} (${RENFORGE_XVFB_SCREEN})..."
    Xvfb "$display" -screen 0 "$RENFORGE_XVFB_SCREEN" >/dev/null 2>&1 &
    RENFORGE_XVFB_PID=$!

    local i
    for i in $(seq 1 30); do
        if _display_accessible "$display"; then
            log_success "Xvfb started on ${display}"
            return 0
        fi
        sleep 0.5
    done

    log_error "Failed to start Xvfb on ${display}"
    return 1
}

# Resolve a working DISPLAY, starting Xvfb on :99 when nothing is available.
# Callers must have sourced logging.sh. Sets DISPLAY and persists cloud.env.
ensure_virtual_display() {
    load_renforge_cloud_env

    if [ -n "${DISPLAY:-}" ] && _display_accessible "$DISPLAY"; then
        log_info "DISPLAY already set and accessible: $DISPLAY"
        persist_renforge_cloud_env
        return 0
    fi

    if [ -n "${DISPLAY:-}" ] && ! _display_accessible "$DISPLAY"; then
        log_warning "DISPLAY=$DISPLAY is set but not accessible; looking for another display"
    fi

    local candidate
    for candidate in "$RENFORGE_DEFAULT_DISPLAY" :1; do
        if _display_accessible "$candidate"; then
            export DISPLAY="$candidate"
            log_success "Reusing existing display $DISPLAY"
            persist_renforge_cloud_env
            return 0
        fi
    done

    if ! command -v xdpyinfo >/dev/null 2>&1; then
        log_error "xdpyinfo not found. Install x11-utils (or equivalent) so the virtual display can be verified."
        return 1
    fi

    export DISPLAY="$RENFORGE_DEFAULT_DISPLAY"
    if ! _start_xvfb "$DISPLAY"; then
        return 1
    fi

    local dimensions
    dimensions="$(xdpyinfo -display "$DISPLAY" | awk '/dimensions:/ {print $2; exit}')"
    log_info "Display dimensions: ${dimensions:-unknown}"
    persist_renforge_cloud_env
}
